[package]
name = "adharva-event-server"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
